language: cpp
sudo: required

git:
  depth: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env: CXX=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-6 # installing clang alone doesn't pull in all the libraries
            - cppcheck
      env: CXX=clang++-4.0

    - os: osx
      osx_image: xcode8
      env:
        - CXX=g++-7
        - BREW="brew update && brew install"

before_install:
    - [ -z $BREW ] && eval $BREW

script:
  - make $CXX
  - which cppcheck && cppcheck --enable=all . || true
