compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-6
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: make fourier.o spectrum.o
