language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env:
        - MATRIX_EVAL="CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources: llvm-toolchain-trusty-4.0
          packages: clang-4.0
      env:
        - MATRIX_EVAL="CXX=clang++-4.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: make fourier.o spectrum.o
